import { defineStore } from "pinia";
import type { Treatment } from "@/types/treatment";

export const useTreatmentsStore = defineStore("treatments", {
  state: () => ({
    treatments: [
      {
        treatmentId: "laser-hair-removal",
        name: "Laser Hair Removal",
        shortDescription:
          "The Prowave hair removal system delivers a specially tailored light source for permanent hair reduction. Cutera's innovative hair removal technology provides effective treatment for a wide range of skin types.",
        category: "laser",
        treatmentAreas: ["legs", "face", "bikini", "underarms", "back"],
        targetResults: ["hair removal", "permanent hair reduction", "smooth skin"],
        status: "active",
        services: [
          {
            serviceId: "hair-removal-full-leg",
            description: "Full Leg",
            targetAreas: ["legs"],
            type: "session",
            price: 5000,
            currency: "ZAR",
          },
          {
            serviceId: "hair-removal-half-leg",
            description: "Half Leg",
            targetAreas: ["legs"],
            type: "session",
            price: 3000,
            currency: "ZAR",
          },
          {
            serviceId: "hair-removal-bikini",
            description: "Bikini",
            targetAreas: ["bikini"],
            type: "variable",
            priceRangeMin: 650,
            priceRangeMax: 1100,
            currency: "ZAR",
          },
          {
            serviceId: "hair-removal-underarm",
            description: "Underarm",
            targetAreas: ["underarms"],
            type: "session",
            price: 500,
            currency: "ZAR",
          },
          {
            serviceId: "hair-removal-lip",
            description: "Lip",
            targetAreas: ["face"],
            type: "session",
            price: 350,
            currency: "ZAR",
          },
          {
            serviceId: "hair-removal-lip-chin",
            description: "Lip and Chin",
            targetAreas: ["face"],
            type: "session",
            price: 500,
            currency: "ZAR",
          },
          {
            serviceId: "hair-removal-full-face",
            description: "Full Face",
            targetAreas: ["face"],
            type: "session",
            price: 1000,
            currency: "ZAR",
          },
          {
            serviceId: "hair-removal-full-back",
            description: "Full Back",
            targetAreas: ["back"],
            type: "session",
            price: 3500,
            currency: "ZAR",
          },
        ],
      },
      {
        treatmentId: "dermapen",
        name: "Dermapen",
        shortDescription:
          "An advanced skin needling technology using multiple needles that vertically pierce the skin with an automatic vibrating function. When moved across the skin's surface, it stimulates natural collagen reproduction. Recommended for fine lines, wrinkles, smoker's lines around the lips, skin tightening, rejuvenation, large pores, and scars.",
        category: "skin-resurfacing",
        treatmentAreas: ["face"],
        targetResults: ["skin texture", "fine lines", "acne scars", "collagen stimulation"],
        status: "active",
        services: [
          {
            serviceId: "dermapen-treatment",
            description: "Treatment",
            targetAreas: ["face"],
            type: "session",
            price: 1900,
            currency: "ZAR",
          },
        ],
      },
      {
        treatmentId: "pearl-fractional",
        name: "Pearl Fractional",
        shortDescription:
          "Advanced fractional laser resurfacing for skin rejuvenation and texture improvement",
        category: "laser",
        treatmentAreas: ["face", "neck", "mouth", "eyes", "lips", "cheeks"],
        targetResults: [
          "skin resurfacing",
          "wrinkle reduction",
          "sun damage",
          "skin texture",
          "fine lines",
        ],
        status: "active",
        services: [
          {
            serviceId: "pearl-fractional-full-face",
            description: "Full Face",
            targetAreas: ["face"],
            type: "session",
            price: 5500,
            currency: "ZAR",
          },
          {
            serviceId: "pearl-fractional-face-neck",
            description: "Full Face and Neck",
            targetAreas: ["face", "neck"],
            type: "session",
            price: 6500,
            currency: "ZAR",
          },
          {
            serviceId: "pearl-fractional-mouth",
            description: "Mouth",
            targetAreas: ["mouth"],
            type: "session",
            price: 4000,
            currency: "ZAR",
          },
          {
            serviceId: "pearl-fractional-under-eyes",
            description: "Under Eyes",
            targetAreas: ["eyes"],
            type: "session",
            price: 3000,
            currency: "ZAR",
          },
          {
            serviceId: "pearl-fractional-lip",
            description: "Lip",
            targetAreas: ["lips"],
            type: "session",
            price: 3000,
            currency: "ZAR",
          },
          {
            serviceId: "pearl-fractional-cheeks",
            description: "Cheeks",
            targetAreas: ["cheeks"],
            type: "session",
            price: 3500,
            currency: "ZAR",
          },
        ],
      },
      {
        treatmentId: "tixel",
        name: "Tixel",
        shortDescription: "Fractional skin resurfacing using thermal energy for skin rejuvenation.",
        category: "skin-resurfacing",
        treatmentAreas: ["face", "neck", "mouth", "eyes", "lips", "cheeks"],
        targetResults: [
          "skin resurfacing",
          "wrinkle reduction",
          "skin tightening",
          "texture improvement",
        ],
        status: "active",
        services: [
          {
            serviceId: "tixel-full-face",
            description: "Full Face",
            targetAreas: ["face"],
            type: "session",
            price: 5000,
            currency: "ZAR",
          },
          {
            serviceId: "tixel-face-neck",
            description: "Full Face and Neck",
            targetAreas: ["face", "neck"],
            type: "session",
            price: 5500,
            currency: "ZAR",
          },
          {
            serviceId: "tixel-mouth",
            description: "Mouth",
            targetAreas: ["mouth"],
            type: "session",
            price: 3500,
            currency: "ZAR",
          },
          {
            serviceId: "tixel-under-eyes",
            description: "Under Eyes",
            targetAreas: ["eyes"],
            type: "session",
            price: 2500,
            currency: "ZAR",
          },
          {
            serviceId: "tixel-lip",
            description: "Lip",
            targetAreas: ["lips"],
            type: "session",
            price: 2500,
            currency: "ZAR",
          },
          {
            serviceId: "tixel-cheeks",
            description: "Cheeks",
            targetAreas: ["cheeks"],
            type: "session",
            price: 2800,
            currency: "ZAR",
          },
        ],
      },
      {
        treatmentId: "limelight",
        name: "Limelight",
        shortDescription:
          "A non-invasive approach to skin rejuvenation that treats pigmentation, redness, and telangiectasia. Limelight can significantly improve skin texture associated with sun damage and aging.",
        category: "laser",
        treatmentAreas: ["face", "neck", "chest", "hands", "arms"],
        targetResults: [
          "sun damage",
          "pigmentation",
          "age spots",
          "skin tone",
          "redness reduction",
        ],
        status: "active",
        services: [
          {
            serviceId: "limelight-face",
            description: "Face",
            targetAreas: ["face"],
            type: "session",
            price: 3900,
            currency: "ZAR",
          },
          {
            serviceId: "limelight-face-neck",
            description: "Face and Neck",
            targetAreas: ["face", "neck"],
            type: "session",
            price: 5500,
            currency: "ZAR",
          },
          {
            serviceId: "limelight-chest",
            description: "Chest",
            targetAreas: ["chest"],
            type: "session",
            price: 3900,
            currency: "ZAR",
          },
          {
            serviceId: "limelight-face-neck-chest",
            description: "Face, Neck and Chest",
            targetAreas: ["face", "neck", "chest"],
            type: "session",
            price: 7500,
            currency: "ZAR",
          },
          {
            serviceId: "limelight-hands",
            description: "Hands",
            targetAreas: ["hands"],
            type: "session",
            price: 1500,
            currency: "ZAR",
          },
          {
            serviceId: "limelight-neck",
            description: "Neck",
            targetAreas: ["neck"],
            type: "session",
            price: 1600,
            currency: "ZAR",
          },
          {
            serviceId: "limelight-forearms",
            description: "Forearms",
            targetAreas: ["arms"],
            type: "session",
            price: 3000,
            currency: "ZAR",
          },
          {
            serviceId: "limelight-full-arms",
            description: "Full Arms",
            targetAreas: ["arms"],
            type: "session",
            price: 5000,
            currency: "ZAR",
          },
        ],
      },
      {
        treatmentId: "peels",
        name: "Peels",
        shortDescription:
          "We offer a variety of peels tailored specifically to each individual's skin. Key benefits of a peel: Restores a radiant complexion, improves fine lines and wrinkles, evens skin tone, brightens a dull complexion, improves skin texture and smoothness, regulates oily skin and dilated pores, and increases cell renewal.",
        category: "chemical-peels",
        treatmentAreas: ["face"],
        targetResults: [
          "exfoliation",
          "skin brightening",
          "texture improvement",
          "anti-aging",
          "acne treatment",
          "pigmentation",
        ],
        status: "active",
        services: [
          {
            serviceId: "retinol-peel",
            description: "Retinol Peel",
            targetAreas: ["face"],
            type: "session",
            price: 1500,
            currency: "ZAR",
          },
          {
            serviceId: "glycolic-peel",
            description: "Glycolic Peel",
            targetAreas: ["face"],
            type: "session",
            price: 1100,
            currency: "ZAR",
          },
          {
            serviceId: "cosmo-peel",
            description: "Cosmo Peel",
            targetAreas: ["face"],
            type: "session",
            price: 1800,
            currency: "ZAR",
          },
          {
            serviceId: "milk-peel",
            description: "Milk Peel",
            targetAreas: ["face"],
            type: "session",
            price: 1100,
            currency: "ZAR",
          },
          {
            serviceId: "gel-peel",
            description: "Gel Peel",
            targetAreas: ["face"],
            type: "session",
            price: 1100,
            currency: "ZAR",
          },
        ],
      },
      {
        treatmentId: "red-light-treatment",
        name: "Red Light",
        shortDescription:
          "A quick, well tolerated and non-invasive treatment. The omnilux red light uses specific wavelengths to stimulates the deeper skin layers to increase the speed and efficiency by which your skin manufactures new collagen. Successfully treats a variety of skin conditions including acne, skin rejuvenation and wound healing.",
        category: "light-therapy",
        treatmentAreas: ["face"],
        targetResults: [
          "collagen stimulation",
          "acne treatment",
          "skin rejuvenation",
          "wound healing",
          "anti-aging",
        ],
        status: "active",
        services: [
          {
            serviceId: "red-light-treatment-session",
            description: "Treatment",
            targetAreas: ["face"],
            type: "session",
            price: 450,
            currency: "ZAR",
          },
        ],
      },
      {
        treatmentId: "ndyag-veins",
        name: "Nd:YAG",
        shortDescription:
          "A laser treatment designed for resolving a variety of vascular conditions. Nd:YAG can treat the following conditions: spider and fine facial veins, telangiectasia, hemangiomas, warts, nail fungus, and port wine stains.",
        category: "laser",
        treatmentAreas: ["legs", "face", "body"],
        targetResults: ["vein removal", "spider veins", "vascular lesions", "thread veins"],
        status: "active",
        services: [
          {
            serviceId: "ndyag-veins-treatment",
            description: "Veins Treatment",
            targetAreas: ["legs", "face", "body"],
            type: "variable",
            priceRangeMin: 1000,
            priceRangeMax: 1500,
            currency: "ZAR",
          },
        ],
      },
    ] as Treatment[],
    loading: false,
    error: null as string | null,
  }),

  getters: {
    getAllTreatments: (state) => state.treatments,
    getTreatmentById: (state) => (treatmentId: string) =>
      state.treatments.find((treatment) => treatment.treatmentId === treatmentId),
  },

  actions: {
    async fetchTreatments() {
      this.loading = true;
      this.error = null;
      try {
        // For now, we're using the hardcoded data in state
        await new Promise((resolve) => setTimeout(resolve, 1000)); // Simulate API delay
      } catch (error) {
        this.error = "Failed to fetch treatments";
        console.error("Error fetching treatments:", error);
      } finally {
        this.loading = false;
      }
    },
  },
});
